version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: developement
    volumes:
      - ./:/app
      - /app/node_modules

    environment:
      - NODE_ENV=developement
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret

    command: ["pnpm", "run", "dev"]
  mongo:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
